import { LookupData } from './lookupsSeed';

import { LookupCategory } from '../models/lookup.model';

// Tools list based on the screenshot
export const TOOLS: readonly LookupData[] = [
  {
    category: LookupCategory.TOOL,
    code: 'CLAMP_600A_AC',
    description: 'Clamp Meter 600A AC',
    id: 117,
    isActive: true,
    isDefault: false,
    name: 'Clamp Meter 600A AC',
    nameArabic: 'مقياس كماشة 600A AC',
    orderId: 1,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'ALLEN_KEYS_STAR_9',
    description: 'Allen Keys Star 9 Pcs',
    id: 118,
    isActive: true,
    isDefault: false,
    name: 'Allen Keys Star 9 Pcs',
    nameArabic: 'مفاتيح ألين نجمة 9 قطع',
    orderId: 2,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'RUBBER_HAMMER',
    description: 'Rubber hammer',
    id: 119,
    isActive: true,
    isDefault: false,
    name: 'Rubber hammer',
    nameArabic: 'مطرقة مطاطية',
    orderId: 3,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'WIRE_PULLING_SPRING',
    description: 'Electrical wire pulling spring',
    id: 120,
    isActive: true,
    isDefault: false,
    name: 'Electrical wire pulling spring',
    nameArabic: 'زنبرك سحب الأسلاك الكهربائية',
    orderId: 4,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'BATTERY_5A',
    description: 'Battery 5 A',
    id: 121,
    isActive: true,
    isDefault: false,
    name: 'Battery 5 A',
    nameArabic: 'بطارية 5 أمبير',
    orderId: 5,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'DUST_EXTRACTOR',
    description: 'Dust Extractor',
    id: 122,
    isActive: true,
    isDefault: false,
    name: 'Dust Extractor',
    nameArabic: 'مستخرج الغبار',
    orderId: 6,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'CLAMP_600A_AC_DC',
    description: 'Clamp Meter 600A AC-DC',
    id: 123,
    isActive: true,
    isDefault: false,
    name: 'Clamp Meter 600A AC-DC',
    nameArabic: 'مقياس كماشة 600A AC-DC',
    orderId: 7,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'ADJUSTABLE_WRENCH_3',
    description: 'Adjustable Wrench 3 Pcs',
    id: 124,
    isActive: true,
    isDefault: false,
    name: 'Adjustable Wrench 3 Pcs',
    nameArabic: 'مفتاح ربط قابل للتعديل 3 قطع',
    orderId: 8,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'SCREW_DRIVER_SET_6',
    description: 'Screw driver Set 6 Pcs',
    id: 125,
    isActive: true,
    isDefault: false,
    name: 'Screw driver Set 6 Pcs',
    nameArabic: 'مجموعة مفكات براغي 6 قطع',
    orderId: 9,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'NOSE_PLIER_2',
    description: 'Nose Plier 2 PCs',
    id: 126,
    isActive: true,
    isDefault: false,
    name: 'Nose Plier 2 PCs',
    nameArabic: 'كماشة أنف 2 قطع',
    orderId: 10,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'SPIRIT_LEVEL',
    description: 'Spirit Level',
    id: 127,
    isActive: true,
    isDefault: false,
    name: 'Spirit Level',
    nameArabic: 'ميزان ماء',
    orderId: 11,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'DRILL_HAMMER',
    description: 'Drill Hammer',
    id: 128,
    isActive: true,
    isDefault: false,
    name: 'Drill Hammer',
    nameArabic: 'مثقاب مطرقة',
    orderId: 12,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'TROLLY_BOX',
    description: 'Trolly box',
    id: 129,
    isActive: true,
    isDefault: false,
    name: 'Trolly box',
    nameArabic: 'صندوق عربة',
    orderId: 13,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'WATER_QUALITY_TESTER',
    description: 'Water quality Tester',
    id: 130,
    isActive: true,
    isDefault: false,
    name: 'Water quality Tester',
    nameArabic: 'مختبر جودة المياه',
    orderId: 14,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'PLIERS_SET_3',
    description: 'Pliers Set 3 Pcs',
    id: 131,
    isActive: true,
    isDefault: false,
    name: 'Pliers Set 3 Pcs',
    nameArabic: 'مجموعة كماشات 3 قطع',
    orderId: 15,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'DIGITAL_CALIPER',
    description: 'Digital Caliper',
    id: 132,
    isActive: true,
    isDefault: false,
    name: 'Digital Caliper',
    nameArabic: 'فرجار رقمي',
    orderId: 16,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'PLIER_CUTTER',
    description: 'Plier Cutter',
    id: 133,
    isActive: true,
    isDefault: false,
    name: 'Plier Cutter',
    nameArabic: 'كماشة قاطعة',
    orderId: 17,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'SOCKET_WRENCH_2',
    description: 'Socket wrench 2 Pcs',
    id: 134,
    isActive: true,
    isDefault: false,
    name: 'Socket wrench 2 Pcs',
    nameArabic: 'مفتاح ربط مأخذ 2 قطع',
    orderId: 18,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'CORDLESS_PRESSURE_WASHER',
    description: 'Cordless Pressure washer',
    id: 135,
    isActive: true,
    isDefault: false,
    name: 'Cordless Pressure washer',
    nameArabic: 'غسالة ضغط لاسلكية',
    orderId: 19,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'VACUUM_MACHINE',
    description: 'Vacuum Machine',
    id: 136,
    isActive: true,
    isDefault: false,
    name: 'Vacuum Machine',
    nameArabic: 'آلة تفريغ',
    orderId: 20,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'SHOCK_WAVE_BIT_56',
    description: 'Shock wave bit 56 Pcs',
    id: 137,
    isActive: true,
    isDefault: false,
    name: 'Shock wave bit 56 Pcs',
    nameArabic: 'بت موجة الصدمة 56 قطعة',
    orderId: 21,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'RATCHET_WRENCH_SET_216',
    description: 'Ratchet and Wrench Set 216 Pcs',
    id: 138,
    isActive: true,
    isDefault: false,
    name: 'Ratchet and Wrench Set 216 Pcs',
    nameArabic: 'مجموعة رافعة ومفتاح 216 قطعة',
    orderId: 22,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'OIL_KETTLE',
    description: 'Oil Kettle',
    id: 139,
    isActive: true,
    isDefault: false,
    name: 'Oil Kettle',
    nameArabic: 'غلاية زيت',
    orderId: 23,
    parentLookupId: null,
  },
  {
    category: LookupCategory.TOOL,
    code: 'PLUMP_LINE',
    description: 'Plump Line',
    id: 140,
    isActive: true,
    isDefault: false,
    name: 'Plump Line',
    nameArabic: 'خط مضخة',
    orderId: 24,
    parentLookupId: null,
  },
];


